; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "OICPP-Plus IDE"
!define PRODUCT_VERSION "1.5.4"
!define PRODUCT_PUBLISHER "qingyingge"
!define PRODUCT_WEB_SITE "https://github.com/qingyingge/oicpp-plus"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\OICPP-Plus IDE.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKCU"

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "nsDialogs.nsh"
!include "WinMessages.nsh"
!include "FileFunc.nsh"

Unicode true

RequestExecutionLevel user

Var CPP_ASSOC_CHECKBOX
Var DESKTOP_SHORTCUT_CHECKBOX
Var CONTEXT_MENU_CHECKBOX
Var UPDATE_SILENT_MODE
Var UPDATE_INSTALL_DIR
Var OICPP_ELEVATED_INSTANCE
Var OICPP_USER_PROFILE
Var OICPP_ORIGINAL_PARAMETERS
Var OICPP_NEEDS_ELEVATION

SetCompressor lzma

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "oicpp-plus.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
!insertmacro MUI_PAGE_LICENSE "LICENSE"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\OICPP-Plus IDE.exe"
; Custom page to set file association for .cpp (shown before Finish page)
Page custom MyCppAssocShow MyCppAssocLeave
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "OICPP-${PRODUCT_VERSION}-Setup.exe"
InstallDir "$LOCALAPPDATA\Programs\OICPP-Plus IDE"
InstallDirRegKey HKCU "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  SetShellVarContext current
  StrCpy $OICPP_USER_PROFILE "$PROFILE"
  StrCpy $OICPP_ELEVATED_INSTANCE "0"
  StrCpy $OICPP_NEEDS_ELEVATION "0"
  ${GetParameters} $OICPP_ORIGINAL_PARAMETERS

  StrCpy $R0 ""
  ${GetOptions} $OICPP_ORIGINAL_PARAMETERS "/OICPP_ELEVATED=" $R0
  ${If} $R0 == "1"
    StrCpy $OICPP_ELEVATED_INSTANCE "1"
  ${EndIf}

  StrCpy $R0 ""
  ${GetOptions} $OICPP_ORIGINAL_PARAMETERS "/OICPP_PROFILE=" $R0
  ${If} $R0 != ""
    StrCpy $OICPP_USER_PROFILE $R0
  ${EndIf}

  StrCpy $UPDATE_SILENT_MODE "0"
  StrCpy $UPDATE_INSTALL_DIR ""

  StrCpy $R1 ""
  ${GetOptions} $OICPP_ORIGINAL_PARAMETERS "/UPDATE_SILENT=" $R1
  ${If} $R1 != ""
    StrCpy $UPDATE_SILENT_MODE $R1
  ${EndIf}

  StrCpy $R2 ""
  ${GetOptions} $OICPP_ORIGINAL_PARAMETERS "/UPDATE_DIR=" $R2
  ${If} $R2 != ""
    StrCpy $UPDATE_INSTALL_DIR $R2
    StrCpy $INSTDIR $R2
  ${EndIf}

  StrCpy $R0 ""
  ${GetOptions} $OICPP_ORIGINAL_PARAMETERS "/OICPP_INSTALL_DIR=" $R0
  ${If} $R0 != ""
    StrCpy $INSTDIR $R0
  ${EndIf}

  ${If} $UPDATE_SILENT_MODE == "1"
    SetSilent silent
    SetAutoClose true
    ${If} $UPDATE_INSTALL_DIR == ""
      ReadRegStr $R3 HKCU "${PRODUCT_DIR_REGKEY}" ""
      ${If} $R3 != ""
        ${GetParent} $R3 $INSTDIR
      ${EndIf}
    ${EndIf}
  ${EndIf}

FunctionEnd
Function IsProtectedInstallDirectory
  StrCpy $OICPP_NEEDS_ELEVATION "0"

  StrCmp /I "$INSTDIR" "$PROGRAMFILES" protected
  StrCpy $R0 "$PROGRAMFILES\"
  StrLen $R1 $R0
  StrCpy $R2 "$INSTDIR" $R1
  StrCmp /I "$R2" "$R0" protected

  StrCmp /I "$INSTDIR" "$PROGRAMFILES32" protected
  StrCpy $R0 "$PROGRAMFILES32\"
  StrLen $R1 $R0
  StrCpy $R2 "$INSTDIR" $R1
  StrCmp /I "$R2" "$R0" protected

  StrCmp /I "$INSTDIR" "$PROGRAMFILES64" protected
  StrCpy $R0 "$PROGRAMFILES64\"
  StrLen $R1 $R0
  StrCpy $R2 "$INSTDIR" $R1
  StrCmp /I "$R2" "$R0" protected
  Goto done

protected:
  StrCpy $OICPP_NEEDS_ELEVATION "1"
done:
FunctionEnd

Function EnsureInstallDirectoryAccess
  Call IsProtectedInstallDirectory
  ${If} $OICPP_NEEDS_ELEVATION == "1"
    ${If} $OICPP_ELEVATED_INSTANCE != "1"
      StrCpy $R0 '$OICPP_ORIGINAL_PARAMETERS /OICPP_ELEVATED=1 /OICPP_PROFILE="$OICPP_USER_PROFILE" /OICPP_INSTALL_DIR="$INSTDIR"'
      ExecShell "runas" "$EXEFILE" "$R0"
      Quit
    ${EndIf}
  ${EndIf}
FunctionEnd
Section "OICPP 主程序" SEC01
  Call EnsureInstallDirectoryAccess
  IfFileExists "$OICPP_USER_PROFILE\.oicpp-plus\settings.json" 0 +3
    CreateDirectory "$TEMP\oicpp_backup"
    CopyFiles "$OICPP_USER_PROFILE\.oicpp-plus\settings.json" "$TEMP\oicpp_backup\settings.json"
  
  SetOutPath "$OICPP_USER_PROFILE\.oicpp-plus"
  SetOverwrite on
  File "dist\win-unpacked\ConsolePauser.exe"
  File "oicpp-plus.ico"
  SetOutPath "$OICPP_USER_PROFILE\.oicpp-plus\LSP"
  SetOverwrite on
  File /r "dist\win-unpacked\resources\clangd\*"
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "dist\win-unpacked\chrome_100_percent.pak"
  File "dist\win-unpacked\chrome_200_percent.pak"

  CreateDirectory "$SMPROGRAMS\OICPP-Plus IDE"
  CreateShortCut "$SMPROGRAMS\OICPP-Plus IDE\OICPP-Plus IDE.lnk" "$INSTDIR\OICPP-Plus IDE.exe" "" "$OICPP_USER_PROFILE\.oicpp-plus\oicpp-plus.ico"

  File "dist\win-unpacked\d3dcompiler_47.dll"
  File "dist\win-unpacked\ffmpeg.dll"
  File "dist\win-unpacked\icudtl.dat"
  File "dist\win-unpacked\libEGL.dll"
  File "dist\win-unpacked\libGLESv2.dll"
  File "dist\win-unpacked\LICENSE.electron.txt"
  File "dist\win-unpacked\LICENSES.chromium.html"
  SetOutPath "$INSTDIR\locales"
  File "dist\win-unpacked\locales\af.pak"
  File "dist\win-unpacked\locales\am.pak"
  File "dist\win-unpacked\locales\ar.pak"
  File "dist\win-unpacked\locales\bg.pak"
  File "dist\win-unpacked\locales\bn.pak"
  File "dist\win-unpacked\locales\ca.pak"
  File "dist\win-unpacked\locales\cs.pak"
  File "dist\win-unpacked\locales\da.pak"
  File "dist\win-unpacked\locales\de.pak"
  File "dist\win-unpacked\locales\el.pak"
  File "dist\win-unpacked\locales\en-GB.pak"
  File "dist\win-unpacked\locales\en-US.pak"
  File "dist\win-unpacked\locales\es-419.pak"
  File "dist\win-unpacked\locales\es.pak"
  File "dist\win-unpacked\locales\et.pak"
  File "dist\win-unpacked\locales\fa.pak"
  File "dist\win-unpacked\locales\fi.pak"
  File "dist\win-unpacked\locales\fil.pak"
  File "dist\win-unpacked\locales\fr.pak"
  File "dist\win-unpacked\locales\gu.pak"
  File "dist\win-unpacked\locales\he.pak"
  File "dist\win-unpacked\locales\hi.pak"
  File "dist\win-unpacked\locales\hr.pak"
  File "dist\win-unpacked\locales\hu.pak"
  File "dist\win-unpacked\locales\id.pak"
  File "dist\win-unpacked\locales\it.pak"
  File "dist\win-unpacked\locales\ja.pak"
  File "dist\win-unpacked\locales\kn.pak"
  File "dist\win-unpacked\locales\ko.pak"
  File "dist\win-unpacked\locales\lt.pak"
  File "dist\win-unpacked\locales\lv.pak"
  File "dist\win-unpacked\locales\ml.pak"
  File "dist\win-unpacked\locales\mr.pak"
  File "dist\win-unpacked\locales\ms.pak"
  File "dist\win-unpacked\locales\nb.pak"
  File "dist\win-unpacked\locales\nl.pak"
  File "dist\win-unpacked\locales\pl.pak"
  File "dist\win-unpacked\locales\pt-BR.pak"
  File "dist\win-unpacked\locales\pt-PT.pak"
  File "dist\win-unpacked\locales\ro.pak"
  File "dist\win-unpacked\locales\ru.pak"
  File "dist\win-unpacked\locales\sk.pak"
  File "dist\win-unpacked\locales\sl.pak"
  File "dist\win-unpacked\locales\sr.pak"
  File "dist\win-unpacked\locales\sv.pak"
  File "dist\win-unpacked\locales\sw.pak"
  File "dist\win-unpacked\locales\ta.pak"
  File "dist\win-unpacked\locales\te.pak"
  File "dist\win-unpacked\locales\th.pak"
  File "dist\win-unpacked\locales\tr.pak"
  File "dist\win-unpacked\locales\uk.pak"
  File "dist\win-unpacked\locales\ur.pak"
  File "dist\win-unpacked\locales\vi.pak"
  File "dist\win-unpacked\locales\zh-CN.pak"
  File "dist\win-unpacked\locales\zh-TW.pak"
  SetOutPath "$INSTDIR"
  File "dist\win-unpacked\OICPP-Plus IDE.exe"
  SetOutPath "$INSTDIR\resources"
  File "dist\win-unpacked\resources\app.asar"
  SetOutPath "$INSTDIR\resources\app.asar.unpacked"
  File /r "dist\win-unpacked\resources\app.asar.unpacked\*"
  SetOutPath "$INSTDIR"
  File "dist\win-unpacked\resources.pak"
  File "dist\win-unpacked\snapshot_blob.bin"
  File "dist\win-unpacked\v8_context_snapshot.bin"
  File "dist\win-unpacked\vk_swiftshader.dll"
  File "dist\win-unpacked\vk_swiftshader_icd.json"
  File "dist\win-unpacked\vulkan-1.dll"
  
  IfFileExists "$TEMP\oicpp_backup\settings.json" 0 +3
    CopyFiles "$TEMP\oicpp_backup\settings.json" "$OICPP_USER_PROFILE\.oicpp-plus\settings.json"
    RMDir /r "$TEMP\oicpp_backup" 
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\OICPP-Plus IDE\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\OICPP-Plus IDE\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKCU "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\OICPP-Plus IDE.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$OICPP_USER_PROFILE\.oicpp-plus\oicpp-plus.ico"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; --- Custom page functions: show a checkbox and on leave, if checked, write file association ---
Function MyCppAssocShow
  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 12u "将 OICPP-Plus IDE 设为 .cpp 文件的默认打开程序："
  Pop $1

  ${NSD_CreateCheckBox} 0 18u 100% 12u "将 OICPP-Plus IDE 设为 .cpp 默认打开程序"
  Pop $CPP_ASSOC_CHECKBOX

  ${NSD_CreateLabel} 0 40u 100% 12u "其他选项："
  Pop $2

  ${NSD_CreateCheckBox} 0 58u 100% 12u "在资源管理器右键菜单加入 OICPP-Plus 操作"
  Pop $CONTEXT_MENU_CHECKBOX
  ${NSD_Check} $CONTEXT_MENU_CHECKBOX

  ${NSD_CreateCheckBox} 0 78u 100% 12u "创建桌面快捷方式"
  Pop $DESKTOP_SHORTCUT_CHECKBOX
  ${NSD_Check} $DESKTOP_SHORTCUT_CHECKBOX

  nsDialogs::Show
FunctionEnd

Function MyCppAssocLeave
  ${NSD_GetState} $CPP_ASSOC_CHECKBOX $0
  StrCmp $0 1 0 +6
    ; Create progid and association under HKCR
    WriteRegStr HKCR ".cpp" "" "OICPPIDE.cpp"
    WriteRegStr HKCR "OICPPIDE.cpp" "" "OICPP-Plus IDE C++ 源文件"
  WriteRegStr HKCR "OICPPIDE.cpp\\DefaultIcon" "" "$INSTDIR\\OICPP-Plus IDE.exe,0"
  ; build the quoted command into a temp variable to avoid parser splitting
  StrCpy $R0 '"$INSTDIR\\OICPP-Plus IDE.exe" "%1"'
  WriteRegStr HKCR "OICPPIDE.cpp\\shell\\open\\command" "" $R0

  ${NSD_GetState} $CONTEXT_MENU_CHECKBOX $2
  StrCmp $2 1 0 +14
    ; File context menu
    WriteRegStr HKCR "*\\shell\\OICPP_OpenFile" "" "在 OICPP-Plus 中打开文件"
    WriteRegStr HKCR "*\\shell\\OICPP_OpenFile" "Icon" "$INSTDIR\\OICPP-Plus IDE.exe,0"
    StrCpy $R1 '"$INSTDIR\\OICPP-Plus IDE.exe" "%1"'
    WriteRegStr HKCR "*\\shell\\OICPP_OpenFile\\command" "" $R1
    ; Folder context menu
    WriteRegStr HKCR "Directory\\shell\\OICPP_OpenFolder" "" "在 OICPP-Plus 中打开文件夹"
    WriteRegStr HKCR "Directory\\shell\\OICPP_OpenFolder" "Icon" "$INSTDIR\\OICPP-Plus IDE.exe,0"
    StrCpy $R2 '"$INSTDIR\\OICPP-Plus IDE.exe" "%1"'
    WriteRegStr HKCR "Directory\\shell\\OICPP_OpenFolder\\command" "" $R2
    ; Background context menu
    WriteRegStr HKCR "Directory\\Background\\shell\\OICPP_OpenFolder" "" "在 OICPP-Plus 中打开文件夹"
    WriteRegStr HKCR "Directory\\Background\\shell\\OICPP_OpenFolder" "Icon" "$INSTDIR\\OICPP-Plus IDE.exe,0"
    StrCpy $R3 '"$INSTDIR\\OICPP-Plus IDE.exe" "%V"'
    WriteRegStr HKCR "Directory\\Background\\shell\\OICPP_OpenFolder\\command" "" $R3

  ${NSD_GetState} $DESKTOP_SHORTCUT_CHECKBOX $1
  StrCmp $1 1 0 +2
    Call CreateDesktopShortcut
FunctionEnd

Function CreateDesktopShortcut
  CreateShortCut "$DESKTOP\OICPP-Plus IDE.lnk" "$INSTDIR\OICPP-Plus IDE.exe" "" "$OICPP_USER_PROFILE\.oicpp-plus\oicpp-plus.ico"
FunctionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从您的计算机移除。"
FunctionEnd

Function un.onInit
  SetShellVarContext current
  StrCpy $OICPP_USER_PROFILE "$PROFILE"
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "确实要完全移除 $(^Name) 及其所有组件吗？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  DeleteRegKey HKCR "*\\shell\\OICPP_OpenFile"
  DeleteRegKey HKCR "Directory\\shell\\OICPP_OpenFolder"
  DeleteRegKey HKCR "Directory\\Background\\shell\\OICPP_OpenFolder"
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\vulkan-1.dll"
  Delete "$INSTDIR\vk_swiftshader_icd.json"
  Delete "$INSTDIR\vk_swiftshader.dll"
  Delete "$INSTDIR\v8_context_snapshot.bin"
  Delete "$INSTDIR\snapshot_blob.bin"
  Delete "$INSTDIR\resources.pak"
  Delete "$INSTDIR\resources\app.asar"
  Delete "$INSTDIR\OICPP-Plus IDE.exe"
  Delete "$INSTDIR\locales\zh-TW.pak"
  Delete "$INSTDIR\locales\zh-CN.pak"
  Delete "$INSTDIR\locales\vi.pak"
  Delete "$INSTDIR\locales\ur.pak"
  Delete "$INSTDIR\locales\uk.pak"
  Delete "$INSTDIR\locales\tr.pak"
  Delete "$INSTDIR\locales\th.pak"
  Delete "$INSTDIR\locales\te.pak"
  Delete "$INSTDIR\locales\ta.pak"
  Delete "$INSTDIR\locales\sw.pak"
  Delete "$INSTDIR\locales\sv.pak"
  Delete "$INSTDIR\locales\sr.pak"
  Delete "$INSTDIR\locales\sl.pak"
  Delete "$INSTDIR\locales\sk.pak"
  Delete "$INSTDIR\locales\ru.pak"
  Delete "$INSTDIR\locales\ro.pak"
  Delete "$INSTDIR\locales\pt-PT.pak"
  Delete "$INSTDIR\locales\pt-BR.pak"
  Delete "$INSTDIR\locales\pl.pak"
  Delete "$INSTDIR\locales\nl.pak"
  Delete "$INSTDIR\locales\nb.pak"
  Delete "$INSTDIR\locales\ms.pak"
  Delete "$INSTDIR\locales\mr.pak"
  Delete "$INSTDIR\locales\ml.pak"
  Delete "$INSTDIR\locales\lv.pak"
  Delete "$INSTDIR\locales\lt.pak"
  Delete "$INSTDIR\locales\ko.pak"
  Delete "$INSTDIR\locales\kn.pak"
  Delete "$INSTDIR\locales\ja.pak"
  Delete "$INSTDIR\locales\it.pak"
  Delete "$INSTDIR\locales\id.pak"
  Delete "$INSTDIR\locales\hu.pak"
  Delete "$INSTDIR\locales\hr.pak"
  Delete "$INSTDIR\locales\hi.pak"
  Delete "$INSTDIR\locales\he.pak"
  Delete "$INSTDIR\locales\gu.pak"
  Delete "$INSTDIR\locales\fr.pak"
  Delete "$INSTDIR\locales\fil.pak"
  Delete "$INSTDIR\locales\fi.pak"
  Delete "$INSTDIR\locales\fa.pak"
  Delete "$INSTDIR\locales\et.pak"
  Delete "$INSTDIR\locales\es.pak"
  Delete "$INSTDIR\locales\es-419.pak"
  Delete "$INSTDIR\locales\en-US.pak"
  Delete "$INSTDIR\locales\en-GB.pak"
  Delete "$INSTDIR\locales\el.pak"
  Delete "$INSTDIR\locales\de.pak"
  Delete "$INSTDIR\locales\da.pak"
  Delete "$INSTDIR\locales\cs.pak"
  Delete "$INSTDIR\locales\ca.pak"
  Delete "$INSTDIR\locales\bn.pak"
  Delete "$INSTDIR\locales\bg.pak"
  Delete "$INSTDIR\locales\ar.pak"
  Delete "$INSTDIR\locales\am.pak"
  Delete "$INSTDIR\locales\af.pak"
  Delete "$INSTDIR\LICENSES.chromium.html"
  Delete "$INSTDIR\LICENSE.electron.txt"
  Delete "$INSTDIR\libGLESv2.dll"
  Delete "$INSTDIR\libEGL.dll"
  Delete "$INSTDIR\icudtl.dat"
  Delete "$INSTDIR\ffmpeg.dll"
  Delete "$INSTDIR\d3dcompiler_47.dll"
  Delete "$INSTDIR\chrome_200_percent.pak"
  Delete "$INSTDIR\chrome_100_percent.pak"
  Delete "$OICPP_USER_PROFILE\.oicpp-plus\ConsolePauser.exe"
  Delete "$OICPP_USER_PROFILE\.oicpp-plus\oicpp-plus.ico"
  RMDir /r "$OICPP_USER_PROFILE\.oicpp-plus\LSP"
  RMDir "$OICPP_USER_PROFILE\.oicpp-plus"

  Delete "$SMPROGRAMS\OICPP-Plus IDE\Uninstall.lnk"
  Delete "$SMPROGRAMS\OICPP-Plus IDE\Website.lnk"
  Delete "$DESKTOP\OICPP-Plus IDE.lnk"
  Delete "$SMPROGRAMS\OICPP-Plus IDE\OICPP-Plus IDE.lnk"

  RMDir "$SMPROGRAMS\OICPP-Plus IDE"
  RMDir /r "$INSTDIR\resources\app.asar.unpacked"
  RMDir "$INSTDIR\resources"
  RMDir "$INSTDIR\locales"
  RMDir "$INSTDIR"
  ; Remove file association keys created by installer (if present)
  DeleteRegKey HKCR ".cpp"
  DeleteRegKey HKCR "OICPPIDE.cpp"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKCU "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
