name: Bug 反馈
description: 反馈 OICPP-Plus 中的错误和问题
title: "[Bug] "
labels: ["待处理"]
assignees:
  - qingyingge
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵时间填写此错误报告！
  
  - type: textarea
    id: description
    attributes:
      label: 描述该错误
      description: 请填写对 bug 的清晰简洁描述。
      placeholder: 详细描述你遇到的问题...
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: 重现该 bug 的步骤
      description: 请提供详细的步骤以重现此问题
      placeholder: |
        1. 前往"..."
        2. 点击"...."
        3. 向下滚动至"...."
        4. 见错误
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 对你期望发生的事情进行清晰简洁的描述。
      placeholder: 你期望发生什么...
    validations:
      required: true
  
  - type: textarea
    id: screenshots
    attributes:
      label: 屏幕截图
      description: 如适用，请添加截图以帮助解释您的问题。
      placeholder: 拖放图片或粘贴图片链接
    validations:
      required: false
  
  - type: input
    id: os
    attributes:
      label: 操作系统
      description: 你使用的操作系统
      placeholder: 例如：Windows 11, NOI Linux 2.0
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: 软件版本
      description: OICPP-Plus 的版本号
      placeholder: 例如：v1.0.0
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: |
        请在 OICPP-Plus 菜单栏-关于-日志上传 中选择出现问题时段的日志，并点击上传。在此填写追踪码。
      placeholder: 请填写追踪码
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: 附加上下文
      description: 在此处添加关于该问题的任何其他上下文信息。
      placeholder: 其他信息...
    validations:
      required: false
