// preload 暴露给渲染层的 API 签名。源自 src/preload.js 的
// exposeInMainWorld('electronAPI', {...}) 块，改 preload 时同步更新。
// 批3：参数已按实现收窄（路径 string、载荷 unknown/Record、回调按 unwrap 形状）；
// 返回值暂用 any：真正的返回类型在批 4 逐个收窄（多数 Promise<T>）。
interface ElectronAPI {
  // 预加载块中的简写属性
  ipcRenderer: {
    send: (channel: string, ...args: unknown[]) => void;
    invoke: (channel: string, ...args: unknown[]) => Promise<unknown>;
    on: (channel: string, listener: (...args: unknown[]) => void) => void;
    once: (channel: string, listener: (...args: unknown[]) => void) => void;
    removeListener: (channel: string, listener: (...args: unknown[]) => void) => void;
    removeAllListeners: (channel: string) => void;
  };
  platform: string;
  // preload.js 实际未暴露此方法（compiler.js 有守卫降级），保留可选契约
  isTestlibSelected?: (version: string) => any;
  openFile(): any;
  openFolder(): any;
  saveFile(filePath: string, content: string): any;
  saveAsFile(content: string): any;
  readFileContent(filePath: string): any;
  readFileBuffer(filePath: string): any;
  readZipTextFiles(zipPath: string): any;
  showItemInFolder(filePath: string): any;
  openPath(targetPath: string, options?: Record<string, unknown>): any;
  showOpenDialog(options: Record<string, unknown>): any;
  showSaveDialog(options: Record<string, unknown>): any;
  saveTempFile(filePath: string, content: string): any;
  saveBinaryTempFile(fileName: string, base64Data: string): any;
  loadTempFile(filePath: string): any;
  deleteTempFile(filePath: string): any;
  getAllSettings(): any;
  getSettings(): any;
  sendSettingsPreview(settings: Record<string, unknown>): any;
  updateSettings(newSettings: Record<string, unknown>): any;
  updateEditorSettings(): any; // deprecated no-op
  resetSettings(): any;
  exportSettings(): any;
  importSettings(): any;
  saveSetting(key: string, value: unknown): any;
  openCompilerSettings(): any;
  openEditorSettings(): any;
  openTemplateSettings(): any;
  openBackupSettings(): any;
  getPlatform(): any;
  getUserHome(): any;
  getUserIconPath(): any;
  getBuildInfo(): any;
  getDownloadedCompilers(): any;
  downloadCompiler(config: Record<string, unknown>): any;
  selectCompiler(version: string): any;
  getDownloadedTestlibs(): any;
  downloadTestlib(config: Record<string, unknown>): any;
  selectTestlib(version: string): any;
  testTestlib(testlibPath: string): any;
  compileFile(options: Record<string, unknown>): any;
  formatCppCode(options: Record<string, unknown>): any;
  runExecutable(options: Record<string, unknown>): any;
  runProgram(executablePathOrOptions: Record<string, unknown> | string, input?: unknown, timeLimit?: number, memoryLimit?: number): any;
  runInteractive(options: Record<string, unknown>): any;
  startCompare(config: Record<string, unknown>): any;
  stopCompare(): any;
  onCompareProgress(cb: (data: { current: number; total: number; testIndex: number }) => void): any;
  onCompareError(cb: (error: { testNumber?: unknown; input?: string; stdOutput?: string; testOutput?: string; inputTruncated?: boolean; stdOutputTruncated?: boolean; testOutputTruncated?: boolean; type?: unknown; code?: string; message?: string }) => void): any;
  onCompareComplete(cb: (result: { completed?: number; failed?: number; stopped?: boolean }) => void): any;
  onCompareWarning(cb: (data: { code?: string; message?: string }) => void): any;
  readDirectory(dirPath: string): any;
  renameFile(oldPath: string, newPath: string, options?: Record<string, unknown>): any;
  deleteFile(filePath: string, options?: Record<string, unknown>): any;
  clearDirectoryContents(dirPath: string): any;
  writeFile(filePath: string, content: string): any;
  createFile(filePath: string, content: string): any;
  createFolder(folderPath: string): any;
  checkFileExists(filePath: string): any;
  getPathInfo(filePath: string): any;
  ensureDirectory(dirPath: string): any;
  watchFile(filePath: string): any;
  unwatchFile(filePath: string): any;
  pathJoin(...paths: string[]): any;
  pathDirname(filePath: string): any;
  getHomeDir(): any;
  ensureDir(dirPath: string): any;
  getTerminalFeatureStatus(): any;
  createTerminal(options: Record<string, unknown>): any;
  writeTerminal(terminalId: string, data: string): any;
  resizeTerminal(terminalId: string, cols: number, rows: number): any;
  killTerminal(terminalId: string): any;
  listTerminals(): any;
  getTerminalTTY(terminalId: string): any;
  onMenuSaveFile(callback: (...args: unknown[]) => void): any;
  onApplySettingsPreview(callback: (...args: unknown[]) => void): any;
  onSettingsApplied(callback: (...args: unknown[]) => void): any;
  onMenuFormatCode(callback: (...args: unknown[]) => void): any;
  onMenuFindReplace(callback: (...args: unknown[]) => void): any;
  onMenuCompile(callback: (...args: unknown[]) => void): any;
  onMenuCompileRun(callback: (...args: unknown[]) => void): any;
  onMenuDebug(callback: (...args: unknown[]) => void): any;
  onMenuNewTempFile(callback: (...args: unknown[]) => void): any;
  onMenuOpenFile(callback: (...args: unknown[]) => void): any;
  onMenuOpenFolder(callback: (...args: unknown[]) => void): any;
  onMenuSaveAs(callback: (...args: unknown[]) => void): any;
  onMenuOpenTerminal(callback: (...args: unknown[]) => void): any;
  onMenuOpenBrowser(callback: (...args: unknown[]) => void): any;
  onMenuNewBrowserTab(callback: (...args: unknown[]) => void): any;
  onMenuAbout(callback: (...args: unknown[]) => void): any;
  onMenuSettings(callback: (...args: unknown[]) => void): any;
  onMenuCheckUpdates(callback: (...args: unknown[]) => void): any;
  getUpdateDownloadStatus(): any;
  onUpdateDownloadStatus(callback: (payload: unknown) => void): any;
  onAppToast(callback: (payload: { message?: string; type?: string }) => void): any;
  onShowDebugDevelopingMessage(callback: (...args: unknown[]) => void): any;
  onSettingsChanged(callback: (event: unknown, settingsType: unknown, newSettings: Record<string, unknown>) => void): any;
  onSettingsReset(callback: (allSettings: InstanceType<typeof import('../js/main.js')>['settings']) => void): any;
  onSettingsImported(callback: (allSettings: InstanceType<typeof import('../js/main.js')>['settings']) => void): any;
  onThemeChanged(callback: (theme: string) => void): any;
  onFileOpened(callback: (event: unknown, data: { fileName?: string; filePath?: string; content?: string }) => void): any;
  onFileSaved(callback: (filePath: unknown, error: unknown) => void): any;
  onFolderOpened(callback: (folderPath: unknown) => void): any;
  reportWorkspacePath(folderPath: string): any;
  onFileOpenedFromArgs(callback: (data: { path?: string; fileName?: string; content?: string; viewType?: string }) => void): any;
  consumeStartupWorkspaceToOpen(): any;
  onExternalFileChange(callback: (payload: unknown) => void): any;
  onSampleTesterCreateProblem(callback: (data: { problemName?: string; samples?: Array<{ input?: string; output?: string; timeLimit?: number }>; OJ?: string }) => void): any;
  onTerminalData(callback: (payload: unknown) => void): any;
  onTerminalExit(callback: (payload: unknown) => void): any;
  getCpuThreads(): any;
  sendFeedback(): any; // deprecated no-op
  listClientLogs(): any;
  uploadClientLog(filePath: string): any;
  getDeviceInfo(): any;
  getEncodedToken(): any;
  openExternal(url: string): any;
  getLanguage(): any;
  getLanguageFile(langCode: string): any;
  getAvailableLanguages(): any;
  onLanguageChanged(callback: (langCode: string) => void): any;
  startIdeLogin(): any;
  getIdeLoginStatus(): any;
  logoutIdeAccount(): any;
  cloudSyncRequest(payload: Record<string, unknown>): any;
  backupSettingsToCloud(): any;
  getSettingsBackupInfo(): any;
  syncSettingsFromCloud(): any;
  onIdeLoginUpdated(callback: (payload: { loggedIn?: boolean; user?: unknown; message?: string }) => void): any;
  onIdeLoginError(callback: (payload: { message?: string }) => void): any;
  getRecentFiles(): any;
  openRecentFile(filePath: string): any;
  getFileHistory(): any;
  addToFileHistory(filePath: string): any;
  openFileFromHistory(filePath: string): any;
  clearFileHistory(): any;
  saveLastOpenTabs(tabs: unknown): any;
  getLastOpenTabs(): any;
  onMenuOpenFileHistory(callback: (...args: unknown[]) => void): any;
  relaunchApp(): any;
  clipboardWriteText(text: string): any;
  clipboardReadText(): any;
  walkDirectory(dirPath: string, options: Record<string, unknown>): any;
  lspStart(options: Record<string, unknown>): any;
  lspStop(): any;
  lspRestart(options: Record<string, unknown>): any;
  lspRequest(method: string, params: unknown, requestId?: unknown): any;
  lspCancel(requestId: unknown): any;
  lspApplyEditResult(requestId: unknown, result: unknown): any;
  lspNotify(method: string, params: unknown): any;
  onLspNotification(callback: (payload: { method?: string; params: Record<string, unknown> }) => void): any;
  onLspApplyEdit(callback: (payload: { requestId?: unknown; edit?: unknown }) => void): any;
  onRequestSaveAll(callback: () => void): any;
  notifySaveAllComplete(): any;
  browserResolveUrl(url: string): any;
  browserGetPageTitle(url: string): any;
  onBrowserOpenNewTab(callback: (payload: unknown) => void): any;
}

interface Window {
  electronAPI: ElectronAPI;
}
