// preload 暴露给渲染层的 API 签名。由 scripts 从 src/preload.js 的
// exposeInMainWorld('electronAPI', {...}) 块机械提取，改 preload 时同步更新。
// 返回值暂用 any：真正的返回类型在 B 线注解式 TS 化时逐个收窄。
interface ElectronAPI {
  // 预加载块中的简写属性（非箭头函数，未被提取脚本覆盖）
  ipcRenderer: any;
  platform: any;
  isTestlibSelected?: any;
  openFile(): any;
  openFolder(): any;
  saveFile(filePath, content): any;
  saveAsFile(content): any;
  readFileContent(filePath): any;
  readFileBuffer(filePath): any;
  readZipTextFiles(zipPath): any;
  showItemInFolder(filePath): any;
  openPath(targetPath, options): any;
  showOpenDialog(options): any;
  showSaveDialog(options): any;
  saveTempFile(filePath, content): any;
  saveBinaryTempFile(fileName, base64Data): any;
  loadTempFile(filePath): any;
  deleteTempFile(filePath): any;
  getAllSettings(): any;
  getSettings(): any;
  sendSettingsPreview(settings): any;
  updateSettings(newSettings): any;
  updateEditorSettings(): any;
  resetSettings(): any;
  exportSettings(): any;
  importSettings(): any;
  saveSetting(key, value): any;
  openCompilerSettings(): any;
  openEditorSettings(): any;
  openTemplateSettings(): any;
  openBackupSettings(): any;
  getPlatform(): any;
  getUserHome(): any;
  getUserIconPath(): any;
  getBuildInfo(): any;
  getDownloadedCompilers(): any;
  downloadCompiler(config): any;
  selectCompiler(version): any;
  getDownloadedTestlibs(): any;
  downloadTestlib(config): any;
  selectTestlib(version): any;
  testTestlib(testlibPath): any;
  compileFile(options): any;
  formatCppCode(options): any;
  runExecutable(options): any;
  runProgram(executablePath, input, timeLimit, memoryLimit): any;
  runInteractive(options): any;
  startCompare(config): any;
  stopCompare(): any;
  onCompareProgress(cb): any;
  onCompareError(cb): any;
  onCompareComplete(cb): any;
  onCompareWarning(cb): any;
  readDirectory(dirPath): any;
  renameFile(oldPath, newPath, options): any;
  deleteFile(filePath, options): any;
  clearDirectoryContents(dirPath): any;
  writeFile(filePath, content): any;
  createFile(filePath, content): any;
  createFolder(folderPath): any;
  checkFileExists(filePath): any;
  getPathInfo(filePath): any;
  ensureDirectory(dirPath): any;
  watchFile(filePath): any;
  unwatchFile(filePath): any;
  pathJoin(...paths): any;
  pathDirname(filePath): any;
  getHomeDir(): any;
  ensureDir(dirPath): any;
  getTerminalFeatureStatus(): any;
  createTerminal(options): any;
  writeTerminal(terminalId, data): any;
  resizeTerminal(terminalId, cols, rows): any;
  killTerminal(terminalId): any;
  listTerminals(): any;
  getTerminalTTY(terminalId): any;
  onMenuSaveFile(callback): any;
  onApplySettingsPreview(callback): any;
  onSettingsApplied(callback): any;
  onMenuFormatCode(callback): any;
  onMenuFindReplace(callback): any;
  onMenuCompile(callback): any;
  onMenuCompileRun(callback): any;
  onMenuDebug(callback): any;
  onMenuNewTempFile(callback): any;
  onMenuOpenFile(callback): any;
  onMenuOpenFolder(callback): any;
  onMenuSaveAs(callback): any;
  onMenuOpenTerminal(callback): any;
  onMenuOpenBrowser(callback): any;
  onMenuNewBrowserTab(callback): any;
  onMenuAbout(callback): any;
  onMenuSettings(callback): any;
  onMenuCheckUpdates(callback): any;
  getUpdateDownloadStatus(): any;
  onUpdateDownloadStatus(callback): any;
  onAppToast(callback): any;
  onShowDebugDevelopingMessage(callback): any;
  onSettingsChanged(callback): any;
  onSettingsReset(callback): any;
  onSettingsImported(callback): any;
  onThemeChanged(callback): any;
  onFileOpened(callback): any;
  onFileSaved(callback): any;
  onFolderOpened(callback): any;
  reportWorkspacePath(folderPath): any;
  onFileOpenedFromArgs(callback): any;
  consumeStartupWorkspaceToOpen(): any;
  onExternalFileChange(callback): any;
  onSampleTesterCreateProblem(callback): any;
  onTerminalData(callback): any;
  onTerminalExit(callback): any;
  getCpuThreads(): any;
  sendFeedback(): any;
  listClientLogs(): any;
  uploadClientLog(filePath): any;
  getDeviceInfo(): any;
  getEncodedToken(): any;
  openExternal(url): any;
  getLanguage(): any;
  getLanguageFile(langCode): any;
  getAvailableLanguages(): any;
  onLanguageChanged(callback): any;
  startIdeLogin(): any;
  getIdeLoginStatus(): any;
  logoutIdeAccount(): any;
  cloudSyncRequest(payload): any;
  backupSettingsToCloud(): any;
  getSettingsBackupInfo(): any;
  syncSettingsFromCloud(): any;
  onIdeLoginUpdated(callback): any;
  onIdeLoginError(callback): any;
  getRecentFiles(): any;
  openRecentFile(filePath): any;
  getFileHistory(): any;
  addToFileHistory(filePath): any;
  openFileFromHistory(filePath): any;
  clearFileHistory(): any;
  saveLastOpenTabs(tabs): any;
  getLastOpenTabs(): any;
  onMenuOpenFileHistory(callback): any;
  relaunchApp(): any;
  clipboardWriteText(text): any;
  clipboardReadText(): any;
  walkDirectory(dirPath, options): any;
  lspStart(options): any;
  lspStop(): any;
  lspRestart(options): any;
  lspRequest(method, params, requestId): any;
  lspCancel(requestId): any;
  lspApplyEditResult(requestId, result): any;
  lspNotify(method, params): any;
  onLspNotification(callback): any;
  onLspApplyEdit(callback): any;
  onRequestSaveAll(callback): any;
  notifySaveAllComplete(): any;
  browserResolveUrl(url): any;
  browserGetPageTitle(url): any;
  onBrowserOpenNewTab(callback): any;
}

interface Window {
  electronAPI: ElectronAPI;
}
